export const EMOJIS=['🦊','🚀','🦉','🦖','🐙','⚡','🧠','🛸'];
const q=(id,title,story,prompt,options,answer,explanation,hint,digit,type='choice')=>({id,title,story,prompt,options,answer,explanation,hint,digit,type});
export const ROOMS=[
 {name:'The power room',topic:'Zero & First Conditional',tag:'Restore the power',intro:'The lab runs on two things: predictable rules and questionable decisions. Find out which is which.',fragment:'4',code:'274',objects:['Cooling unit','Emergency switch'],positions:[[22,45],[69,54]],puzzles:[
 q('r0a','A very predictable machine','A frost-covered note is stuck to the cooling unit. Complete its operating rule.','Whenever the coolant reaches 0°C, …',['it freezes.','it will have frozen.','it would freeze.'],0,'A general rule uses present simple in both clauses: If the coolant reaches 0°C, it freezes.','This happens every time, not just on one future occasion.','2'),
 q('r0b','One possible future','The emergency switch can still save the generator. Choose the sentence that expresses a real future possibility.','If we restart the generator now, …',['the portal would have opened.','the portal will open.','the portal opened yesterday.'],1,'First Conditional: if + present simple → will + base verb. The restart is still possible.','Use a present tense after if, even when talking about the future.','7') ]},
 {name:'The possibility chamber',topic:'Second Conditional',tag:'Imagine another present',intro:'This room contains things that could exist. A silent alarm. A polite printer. A professor who reads instructions.',fragment:'8',code:'358',objects:['Gravity dial','Robot assistant'],positions:[[46,35],[15,68]],puzzles:[
 q('r1a','A lighter problem','Gravity is normal, and you cannot reach the ceiling hatch. Build an imaginary alternative.','If gravity ___ weaker, we ___ reach the hatch.',['is / will','had been / will','were / could'],2,'Second Conditional imagines a different present: If gravity were weaker, we could reach the hatch. Could expresses ability.','The situation is imaginary now. Formal English uses were for all subjects.','3','build'),
 q('r1b','Advice from a tiny robot','PIP, the robot, is holding a suspiciously large wrench. Give it sensible hypothetical advice.','If I were you, …',['I would check the small switch first.','I will checked the small switch first.','I had checked the small switch first.'],0,'If I were you, I would… is a common Second Conditional structure for advice.','After would, use the base form of the verb.','5') ]},
 {name:'The yesterday archive',topic:'Third Conditional',tag:'Reconstruct the accident',intro:'Yesterday cannot be changed. Unless you own a time machine. Unfortunately, yours currently makes toast.',fragment:'6',code:'916',objects:['Incident report','Security recording'],positions:[[76,62],[30,37]],puzzles:[
 q('r2a','The missing label','Yesterday, the professor did not label the red button. PIP pressed it and opened a prehistoric portal.','If the professor ___ the button, PIP ___ it.',['labels / will not press','had labelled / would not have pressed','labelled / would not press'],1,'Third Conditional imagines a different past: if + past perfect → would have + past participle. Neither event actually happened this way.','Both the condition and its imagined result belong to yesterday.','9','build'),
 q('r2b','What really happened?','The recording says: “If we had charged the battery, the machine would have worked.” Decode the real history.','Which pair belongs in the incident report?',['We charged it. The machine worked.','We did not charge it. The machine worked.','We did not charge it. The machine did not work.'],2,'The sentence imagines an unreal past: charging did not happen, and the intended result did not happen.','Third Conditional often describes a missed opportunity or regret.','1') ]},
 {name:'The timeline fracture',topic:'Mixed Conditionals',tag:'Connect cause and consequence',intro:'Yesterday is leaking into today. Meanwhile, the professor’s permanent habits are causing trouble in the past.',fragment:'2',code:'682',objects:['Present-day monitor','Past-event scanner'],positions:[[64,35],[26,61]],puzzles:[
 q('r3a','Yesterday → now','You ignored the map yesterday. You are lost now. Connect the past cause to the present result.','If we ___ the map yesterday, we ___ lost now.',['had followed / would not be','follow / will not be','followed / would not have been'],0,'Past → present mixed conditional: if + past perfect → would + base verb. Yesterday is the cause; now is the result.','Read the time clues: yesterday in the condition, now in the result.','6','build'),
 q('r3b','A lasting trait → yesterday','The professor is generally impatient. That is why he skipped the safety check yesterday.','If he ___ more patient, he ___ the check yesterday.',['had been / will not skip','were / would not have skipped','is / would not skip'],1,'Present → past mixed conditional: if + past simple → would have + past participle. His general character explains a past event.','A general trait uses the unreal present form; yesterday’s result needs would have.','8','build') ]},
 {name:'The mirror vault',topic:'Inverted Conditionals',tag:'Open the formal protocol',intro:'The vault is terribly formal. It refuses to recognise the word “if”. Move the auxiliary to the front instead.',fragment:'5',code:'4375',objects:['Future protocol','Hypothesis protocol','History protocol'],positions:[[23,43],[49,32],[76,61]],puzzles:[
 q('r4a','A polite contingency','Rewrite the emergency instruction without if.','If you need assistance, press the blue button.',['Would you need assistance, press the blue button.','Had you need assistance, press the blue button.','Should you need assistance, press the blue button.'],2,'Should you need… is a formal conditional equivalent of If you need… . Use the base form after should.','For a possible future contingency, begin with Should.','4'),
 q('r4b','A formal imaginary future','The vault asks you to imagine a shutdown. Keep the meaning, remove if.','If the machine were to fail, we would use the backup.',['Were the machine to fail, we would use the backup.','Had the machine fail, we would use the backup.','Should the machine failed, we would use the backup.'],0,'Were + subject + to-infinitive forms a formal hypothetical conditional: Were the machine to fail… .','Keep were to fail, but put were before the subject.','3'),
 q('r4c','An elegant regret','One final protocol is written in yesterday’s ink.','If we had checked the coordinates, we would have arrived safely.',['Should we checked the coordinates, we would have arrived safely.','Had we checked the coordinates, we would have arrived safely.','Were we checked the coordinates, we would have arrived safely.'],1,'Past inversion: Had + subject + past participle. Had we checked… replaces If we had checked… .','Move had before we. Keep checked in the past participle form.','7') ]},
 {name:'The return chamber',topic:'Choose your future',tag:'Bring the present back',intro:'The portal is almost stable. You need one practical promise and one reminder that this entire situation was avoidable.',fragment:'1',code:'591',objects:['Navigation console','Professor’s recorder'],positions:[[48,43],[78,64]],puzzles:[
 q('r5a','Make a workable plan','Build the team’s promise. Your action is possible, and its result lies ahead.','If we ___ the correct coordinates, we ___ home.',['entered / would have returned','enter / will return','had entered / return'],1,'A real future plan uses First Conditional: If we enter the correct coordinates, we will return home.','This is a real choice you can make now, not a regret.','5','build'),
 q('r5b','Leave a message for yesterday','The coordinates were wrong yesterday. The crew arrived in the wrong century. Record the alternative history.','If we ___ the coordinates, we ___ in the wrong century.',['check / will not land','checked / would not land','had checked / would not have landed'],2,'Third Conditional: If we had checked the coordinates, we would not have landed in the wrong century.','An unreal past cause needs had + past participle. Its result needs would have.','9','build') ]}
];
const b=(id,title,prompt,options,answer,explanation)=>({id,title,prompt,options,answer,explanation,story:'Optional research. Your main mission result will not change.',hint:explanation,type:'choice'});
export const BONUS=[
b('b0','Unless','You cannot enter unless you have a pass. This means…',['You can enter without a pass.','If you do not have a pass, you cannot enter.','You cannot enter if you have a pass.'],1,'Unless means if…not. Avoid adding an unnecessary second negative.'),
b('b1','As long as / so long as','Choose the condition for permission.',['You can borrow PIP as long as you return it.','You can borrow PIP even though you return it.','You can borrow PIP whether you return it.'],0,'As long as and so long as introduce a requirement: permission depends on returning PIP.'),
b('b2','Provided / providing that','You may open the vault ___ you wear safety gloves.',['even','provided that','whether'],1,'Provided (that) and providing (that) introduce a condition, often in a more formal style.'),
b('b3','On condition that','The professor will help on condition that you keep his secret. What must you do?',['Tell everyone.','Help without any requirement.','Keep his secret.'],2,'On condition that introduces a firm requirement.'),
b('b4','Even if','We will continue even if the lights go out. What changes the decision?',['The lights going out.','Neither outcome: we will continue either way.','We continue only when the lights go out.'],1,'Even if introduces a condition that does not change the result.'),
b('b5','Only if','Only if you enter the right code ___ the vault open.',['will','would have','it will'],0,'When Only if starts this sentence, the main clause is inverted: Only if you enter the right code will the vault open.'),
b('b6','Whether … or not','We will rescue PIP whether or not it apologises. This means…',['PIP must apologise first.','We will never rescue PIP.','We will rescue PIP in either case.'],2,'Whether…or not covers both possibilities without changing the outcome.'),
b('b7','In case','Take a torch in case the lights fail. Why take it now?',['As preparation for a possible problem.','Because the lights have definitely failed.','Only after the lights fail.'],0,'In case describes a precaution. If the lights fail, use the torch describes an action dependent on that event.'),
b('b8','Suppose / supposing','Supposing you ___ a time machine, where would you go?',['have had','had','will have'],1,'Suppose and supposing introduce imagined situations. Had matches the hypothetical would go.'),
b('b9','Without / but for','But for your help, we would have failed. What actually happened?',['You did not help.','We failed despite your help.','You helped us avoid failure.'],2,'But for your help and Without your help can replace If you had not helped us in this context.'),
b('b10','Otherwise','Hurry up; otherwise, we will miss the portal. Otherwise means…',['If we do not hurry up.','Even if we hurry up.','Because we hurried up.'],0,'Otherwise introduces the consequence if the previous instruction or condition is not met.'),
b('b11','Imperative + and / or','Check the map, ___ you will get lost.',['and','or','provided'],1,'An imperative + or warns about a result if you do not follow the instruction. Check the map and you will find the route gives the positive consequence.'),
b('b12','Given / failing to','Given enough time, we could fix it. This is closest to…',['If we were given enough time, we could fix it.','We fixed it yesterday.','We cannot fix it under any circumstances.'],0,'Given enough time expresses a condition. Failing to prepare, you risk failure similarly links a failure to prepare with a possible consequence.'),
b('b13','Wish / if only','I wish I ___ that red button yesterday.',['do not press','had not pressed','would not pressed'],1,'Wish / if only + past perfect expresses regret about the past. I wish I were home imagines a different present; I wish PIP would listen requests a change in behaviour.'),
b('b14','Would rather','I would rather you ___ the green button now.',['pressed','had press','will press'],0,'Would rather + a different subject + past simple expresses a present or future preference.'),
b('b15','It is high time','It is high time we ___ this machine.',['will repair','had repair','repaired'],2,'It is (high) time + past simple says that something should happen now, or is overdue.'),
b('b16','As if / as though','PIP acts as if it ___ everything, but it does not.',['will know','knew','has know'],1,'As if / as though + unreal past can mark a contrast with reality. For an earlier unreal event: It acted as though it had never seen us.')
];
export const RECAP=[
['Zero','If + present simple → present simple','Rules and repeated facts: If the coolant reaches 0°C, it freezes.'],
['First','If + present simple → will / may / can + base verb','A real future possibility: If we restart the generator, the portal will open.'],
['Second','If + past simple → would / could / might + base verb','An imaginary present or future: If gravity were weaker, we could reach the hatch.'],
['Third','If + past perfect → would have + past participle','An alternative past: If we had checked the map, we would have arrived safely.'],
['Mixed: past → present','If + past perfect → would + base verb','If we had followed the map yesterday, we would not be lost now.'],
['Mixed: present → past','If + past simple → would have + past participle','If he were more patient, he would not have skipped the check yesterday.'],
['Inversion','Should you need… / Were it to fail… / Had we known…','Remove if and put should, were or had before the subject. The time and meaning still matter.']
];
export const CIPHERS=[
 {message:'UJNF',rule:'Every letter is one step ahead in the alphabet. Move each one back.',options:['TIME','TIDE','TEAM'],answer:0},
 {message:'TSAP',rule:'The mirror wrote this destination backwards.',options:['POST','PAST','PATS'],answer:1},
 {message:'Never Open Windows',rule:'The first letter of each word tells you when to travel.',options:['NEW','NOT','NOW'],answer:2},
 {message:'19 · 1 · 6 · 5',rule:'Use A = 1, B = 2, C = 3… to decode the safe route.',options:['SAVE','SAFE','SAME'],answer:1},
 {message:'EMOH',rule:'The mirror vault reverses everything. Read from right to left.',options:['HOME','HOPE','MORE'],answer:0},
 {message:'– / · / ·–',rule:'PIP’s tiny Morse guide: T = –; E = ·; A = ·–. The slashes separate letters.',options:['EAT','ATE','TEA'],answer:2}
];
