import * as api from './backend.js';
import * as classes from './classroom.js';
import {analyseTeams,QUESTIONS} from './analytics.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=s=>s?new Date(s).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}):'—';
const duration=ms=>Number.isFinite(ms)?`${(ms/1000).toFixed(1)} s`:'Not recorded';
const joinLink=code=>`${location.origin}${location.pathname}#home?code=${encodeURIComponent(code)}`;
let sessions=[],view='active',query='';
export async function mountTeacher(root){
 if(api.configured&&(!api.currentUser()||api.currentUser().is_anonymous)){login(root);return;}
 try{sessions=await classes.listSessions();render(root);}catch(e){if(api.configured)login(root,e.message);else root.textContent=e.message;}
}
function login(root,error=''){
 root.innerHTML=`<form id="login-form" class="session-box" style="max-width:480px"><h2>Teacher sign-in</h2><label class="field">Email<input id="email" type="email" autocomplete="username" required></label><label class="field">Password<input id="password" type="password" autocomplete="current-password" required></label><button class="btn">Sign in →</button><p id="login-error" class="error" role="alert">${esc(error)}</p><p class="small muted">Use your teacher account. Students only need the class code.</p></form>`;
 root.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;try{await api.login(root.querySelector('#email').value,root.querySelector('#password').value);sessions=await classes.listSessions();render(root);}catch(err){root.querySelector('#login-error').textContent=err.message;btn.disabled=false;}};
}
function render(root){
 root.innerHTML=`<div class="row between"><p class="muted">${api.configured?`Signed in as ${esc(api.currentUser()?.email)}`:'Saved on this device. Connect Supabase before using multiple phones.'}</p>${api.configured?'<button class="ghost" id="logout">Sign out</button>':''}</div>
 <form id="create-session" class="session-box"><h2>A new expedition</h2><div class="form-grid"><label class="field">Class / session name<input id="class-title" placeholder="Year 9A · Conditionals" maxlength="60" required></label><label class="field">Game duration<select id="duration"><option value="25">25 minutes</option><option value="30" selected>30 minutes</option><option value="35">35 minutes</option><option value="40">40 minutes</option></select></label></div><button class="btn">Create class session →</button><p class="small muted spaced">Each team starts its own countdown after the briefing. Every session keeps its own dated history.</p><p id="create-error" class="error" role="alert"></p></form>
 <div class="teacher-filter row between"><div class="row" role="group" aria-label="Session view"><button class="btn ${view==='active'?'':'secondary'}" data-view="active">Active classes</button><button class="btn ${view==='history'?'':'secondary'}" data-view="history">History</button><button class="btn ${view==='all'?'':'secondary'}" data-view="all">All</button></div><label class="field">Find a class or date<input type="search" id="session-search" value="${esc(query)}" placeholder="Year 9A or 26 Sept"></label></div><p class="small muted">Times shown in ${esc(Intl.DateTimeFormat().resolvedOptions().timeZone)}.</p><div id="sessions"></div>`;
 if(root.querySelector('#logout'))root.querySelector('#logout').onclick=async()=>{await api.logout();login(root);};
 root.querySelector('#create-session').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;try{await classes.createSession(root.querySelector('#class-title').value.trim(),Number(root.querySelector('#duration').value));sessions=await classes.listSessions();view='active';query='';render(root);}catch(err){root.querySelector('#create-error').textContent=err.message;btn.disabled=false;}};
 root.querySelectorAll('[data-view]').forEach(btn=>btn.onclick=()=>{view=btn.dataset.view;render(root);});
 root.querySelector('#session-search').oninput=e=>{query=e.target.value;cards(root);};cards(root);
}
function cards(root){
 const shown=sessions.filter(s=>(view==='all'||Boolean(s.archived_at)===(view==='history'))&&`${s.title} ${s.code} ${stamp(s.created_at)} ${s.archived_at?stamp(s.archived_at):''}`.toLowerCase().includes(query.toLowerCase()));
 const box=root.querySelector('#sessions');
 box.innerHTML=shown.length?shown.map(s=>`<section class="session-box"><div class="row between"><h3>${esc(s.title)}</h3><span class="status-label">${s.archived_at?'Archived':s.is_open?'Open for teams':'Entry closed'}</span></div><p class="session-dates">Started ${stamp(s.created_at)}${s.archived_at?` · Archived ${stamp(s.archived_at)}`:''}</p><div class="session-code">${esc(s.code)}</div><p class="small muted">${s.minutes} minutes · ${s.team_count} teams</p>${!s.archived_at?`<div class="row"><div class="qr-slot" data-code="${esc(s.code)}"></div><div style="flex:1;min-width:200px"><label class="field">Share this link<input class="link-field" readonly value="${esc(joinLink(s.code))}" aria-label="Session join link"></label><button class="ghost" data-copy="${esc(s.code)}">Copy link</button></div></div>`:''}<div class="row spaced"><a class="btn" href="#board?code=${esc(s.code)}">${s.archived_at?'View final board':'Open live board'} →</a><button class="btn secondary" data-report="${s.id}">Learning report</button><button class="btn secondary" data-export="${s.id}">Export results</button><button class="btn amber" data-reset="${s.id}">Reset for another class</button>${!s.archived_at?`<button class="ghost" data-close="${s.id}" data-open="${!s.is_open}">${s.is_open?'Close entry':'Reopen entry'}</button><button class="ghost" data-archive="${s.id}">End & archive</button>`:''}<button class="ghost delete-class" data-delete="${s.id}">Delete class</button></div><p class="small muted spaced">${s.archived_at?'Results are preserved. Start a new class to get a fresh code and timer.':'Reset creates a new session and archives this one. No results are deleted.'}</p><p class="session-error error" role="alert"></p><div data-report-slot="${s.id}"></div></section>`).join(''):'<div class="empty-state">No sessions match this view.</div>';
 const action=(button,fn)=>async()=>{button.disabled=true;try{await fn();}catch(err){button.closest('.session-box').querySelector('.session-error').textContent=err.message;}finally{button.disabled=false;}};
 box.querySelectorAll('[data-close]').forEach(b=>b.onclick=action(b,async()=>{await classes.setOpen(b.dataset.close,b.dataset.open==='true');sessions=await classes.listSessions();render(root);}));
 box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=action(b,async()=>{await navigator.clipboard.writeText(joinLink(b.dataset.copy));b.textContent='Copied';}));
 box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteDialog(root,sessions.find(s=>s.id===b.dataset.delete)));
 box.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>sessionDialog(root,sessions.find(s=>s.id===b.dataset.reset),'reset'));
 box.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>sessionDialog(root,sessions.find(s=>s.id===b.dataset.archive),'archive'));
 box.querySelectorAll('[data-report]').forEach(b=>b.onclick=action(b,async()=>{const slot=box.querySelector(`[data-report-slot="${b.dataset.report}"]`);slot.innerHTML='<p class="muted">Loading report…</p>';const data=await classes.sessionReport(b.dataset.report);slot.innerHTML=reportHtml(data);slot.scrollIntoView({behavior:'smooth',block:'start'});}));
 box.querySelectorAll('[data-export]').forEach(b=>b.onclick=action(b,async()=>download(await classes.sessionReport(b.dataset.export))));
 box.querySelectorAll('.qr-slot').forEach(el=>{if(window.qrcode){const q=window.qrcode(0,'M');q.addData(joinLink(el.dataset.code));q.make();el.innerHTML=q.createSvgTag({cellSize:3,margin:12,scalable:true});el.classList.add('qr');el.setAttribute('aria-label','Session QR code');}});
}
function sessionDialog(root,s,kind){
 const dialog=document.createElement('dialog');dialog.className='map-dialog teacher-dialog';
 dialog.innerHTML=`<form><h2>${kind==='reset'?'A fresh start. History kept.':'End this class session?'}</h2><p>${esc(s.title)} will be archived with its results and timestamps. ${!s.archived_at?'Teams still playing will be stopped.':''}</p>${kind==='reset'?`<label class="field">New class name<input name="title" value="${esc(s.title)}" maxlength="60" required></label><label class="field">Minutes<input name="minutes" type="number" value="${s.minutes}" min="5" max="60" required></label>`:''}<div class="row"><button class="btn" type="submit">${kind==='reset'?'Archive & create new class':'End & archive'}</button><button class="btn secondary" type="button" id="cancel-session">Cancel</button></div><p class="error" role="alert"></p></form>`;
 document.body.append(dialog);dialog.showModal();dialog.querySelector('#cancel-session').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=e.target.querySelector('[type=submit]');submit.disabled=true;try{if(kind==='reset')await classes.resetSession(s.id,e.target.elements.title.value.trim(),Number(e.target.elements.minutes.value));else await classes.archiveSession(s.id);sessions=await classes.listSessions();view=kind==='reset'?'active':'history';query='';dialog.close();render(root);}catch(err){dialog.querySelector('.error').textContent=err.message;submit.disabled=false;}};
}
export function reportHtml(data){
 const a=analyseTeams(data.teams),ranked=[...a.rows].sort((x,y)=>y.wrong-x.wrong),max=Math.max(1,...ranked.map(q=>q.wrong));
 return `<section class="learning-report"><div class="eyebrow">Learning report / ${esc(data.session.title)}</div><h2>Where did time get lost?</h2><p class="small muted">${stamp(data.session.created_at)} · ${a.teamCount} teams · Report updated ${stamp(Date.now())}</p><div class="report-summary"><article><span>Most mistakes</span><strong>${ranked[0]?.wrong?esc(ranked[0].title):'No mistakes recorded'}</strong><small>${ranked[0]?.wrong||0} wrong answers</small></article><article><span>Fastest typical solution</span><strong>${a.quickest?esc(a.quickest.title):'Not enough timing data'}</strong><small>${a.quickest?`${duration(a.quickest.medianMs)} median · ${a.quickest.timings.length} correct teams · ${Math.round(a.quickest.firstTryRate*100)}% correct first try`:'Requires correct timed answers from at least 2 teams.'}</small></article></div>
 <h3>Most common mistakes</h3><div class="mistake-chart" role="img" aria-label="Wrong answer counts by question; detailed figures follow below">${ranked.filter(q=>q.wrong).map(q=>`<div class="chart-row"><span>${esc(q.title)}</span><div class="chart-track"><i style="width:${q.wrong/max*100}%"></i></div><b>${q.wrong}</b></div>`).join('')||'<p class="muted">No wrong answers recorded yet.</p>'}</div>
 <p class="small muted">Speed is a clue, not proof of understanding. Compare median time, correct-first-try rate and sample size. Times run from the first opening of a question to its correct answer, including discussion, retries and waiting periods. Old sessions without timestamps show “Not recorded”.</p>
 <h3>Each team’s fastest correct response</h3><div class="table-scroll"><table><thead><tr><th>Team</th><th>Question</th><th>Time</th><th>Attempt</th><th>Answered at</th></tr></thead><tbody>${a.fastest.map(f=>`<tr><td>${esc(f.emoji)} ${esc(f.team)}</td><td>${esc(f.title)}</td><td>${duration(f.ms)}</td><td>${f.attempt}</td><td>${stamp(f.at)}</td></tr>`).join('')||'<tr><td colspan="5">No timed correct responses yet.</td></tr>'}</tbody></table></div>
 <h3>Question breakdown</h3><div class="table-scroll"><table><thead><tr><th>Question / topic</th><th>Wrong answers</th><th>Correct first try</th><th>Median time / samples</th><th>Most selected wrong answer</th></tr></thead><tbody>${a.rows.map(q=>`<tr><td>${esc(q.title)}<small>${esc(q.topic)}</small></td><td>${q.wrong}</td><td>${q.seenTeams?`${Math.round(q.firstTryRate*100)}% (${q.firstTry}/${q.seenTeams})`:'—'}</td><td>${duration(q.medianMs)} / ${q.timings.length}</td><td>${q.topWrong?`${esc(q.options[q.topWrong[0]])} (${q.topWrong[1]})`:'—'}</td></tr>`).join('')}</tbody></table></div></section>`;
}
function download(data){
 const rows=[['Session','Created','Team','Emoji','Status','Question','Selected answer','Correct','Attempt','Elapsed seconds','Answered at']];
 for(const t of data.teams){const s=t.state;for(const e of s.answerEvents||[])rows.push([data.session.title,data.session.created_at,t.name,t.emoji,s.status,e.question,QUESTIONS.find(q=>q.id===e.question)?.options[e.selected]??e.selected,e.correct,e.attempt,Number.isFinite(e.elapsedMs)?e.elapsedMs/1000:'',new Date(e.at).toISOString()]);if(!s.answerEvents?.length)rows.push([data.session.title,data.session.created_at,t.name,t.emoji,s.status,'No detailed timing history']);}
 const safe=x=>'"'+String(x??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const blob=new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`if-lab-${data.session.code}-${data.session.created_at.slice(0,10)}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);
}

function deleteDialog(root,s){
 const dialog=document.createElement('dialog');dialog.className='map-dialog teacher-dialog';
 dialog.setAttribute('aria-labelledby','delete-class-title');
 dialog.innerHTML=`<form><h2 id="delete-class-title">Delete this class?</h2><p><strong>${esc(s.title)}</strong> · ${esc(s.code)}<br>Created ${stamp(s.created_at)}</p><p>This permanently deletes this class, all its teams and their results. It cannot be undone. Other classes are kept.</p><p class="small muted">Export results first if you want a copy. Teams still playing will no longer be able to save to this class.</p><div class="row"><button class="btn secondary" type="button" id="cancel-delete" autofocus>Cancel</button><button class="btn danger" type="submit">Delete class permanently</button></div><p class="error" role="alert"></p></form>`;
 document.body.append(dialog);dialog.showModal();dialog.querySelector('#cancel-delete').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
 dialog.querySelector('form').onsubmit=async e=>{
  e.preventDefault();const btn=e.target.querySelector('[type=submit]');btn.disabled=true;
  try{await classes.deleteSession(s.id);sessions=await classes.listSessions();dialog.close();render(root);}
  catch(err){dialog.querySelector('.error').textContent=err.message.includes('delete_lab')?'Database update required: run supabase/enable-class-deletion.sql in Supabase SQL Editor, then try again.':err.message;btn.disabled=false;}
 };
}
